<?php

namespace App\Enums;

use BenSampo\Enum\Enum;

final class MobileRegex extends Enum
{
    const ALL_MOBILE_REGEX = [
        'AE' => self::AE,
        'SA' => self::SA,
        'OM' => self::OM,
        'KW' => self::KW,
        'QA' => self::QA,
        'BH' => self::BH,
        'US' => self::US,
        'UK' => self::UK,
        'EG' => self::EG,
        'DE' => self::DE,
        'FR' => self::FR,
        'CN' => self::CN,
        'IN' => self::IN,
        'AU' => self::AU,
        'BR' => self::BR,
        'ZA' => self::ZA,
        'JP' => self::JP,
        'CA' => self::CA,
        'MX' => self::MX,
        'RU' => self::RU,
        'IT' => self::IT,
        'ES' => self::ES,
        'NL' => self::NL,
        'SE' => self::SE,
        'NO' => self::NO,
        'DK' => self::DK,
        'FI' => self::FI,
        'BE' => self::BE,
        'CH' => self::CH,
        'AT' => self::AT,
        'PT' => self::PT,
        'GR' => self::GR,
        'IE' => self::IE,
        'PL' => self::PL,
        'CZ' => self::CZ,
        'HU' => self::HU,
        'SK' => self::SK,
        'RO' => self::RO,
        'BG' => self::BG,
        'HR' => self::HR,
        'SI' => self::SI,
        'LT' => self::LT,
        'LV' => self::LV,
        'EE' => self::EE,
        'TR' => self::TR,
        'IL' => self::IL,
        'JO' => self::JO,
        'LB' => self::LB,
        'SY' => self::SY,
        'IQ' => self::IQ,
        'IR' => self::IR,
        'PK' => self::PK,
        'BD' => self::BD,
        'LK' => self::LK,
        'NP' => self::NP,
        'AF' => self::AF,
        'UZ' => self::UZ,
        'KZ' => self::KZ,
        'KG' => self::KG,
        'TJ' => self::TJ,
        'TM' => self::TM,
        'AZ' => self::AZ,
        'GE' => self::GE,
        'AM' => self::AM,
        'BY' => self::BY,
        'MD' => self::MD,
        'UA' => self::UA,
        'TH' => self::TH,
        'VN' => self::VN,
        'MY' => self::MY,
        'SG' => self::SG,
        'ID' => self::ID,
        'PH' => self::PH,
        'KR' => self::KR,
        'TW' => self::TW,
        'HK' => self::HK,
        'MO' => self::MO,
        'NZ' => self::NZ,
        'FJ' => self::FJ,
        'PG' => self::PG,
        'SB' => self::SB,
        'VU' => self::VU,
        'NC' => self::NC,
        'PF' => self::PF,
        'WS' => self::WS,
        'TO' => self::TO,
        'KI' => self::KI,
        'TV' => self::TV,
        'NR' => self::NR,
        'PW' => self::PW,
        'FM' => self::FM,
        'MH' => self::MH,
        'CK' => self::CK,
        'NU' => self::NU,
        'TK' => self::TK,
        'WF' => self::WF,
        'AS' => self::AS,
        'GU' => self::GU,
        'MP' => self::MP,
        'VI' => self::VI,
        'PR' => self::PR,
        'DO' => self::DO,
        'CU' => self::CU,
        'JM' => self::JM,
        'HT' => self::HT,
        'TT' => self::TT,
        'BB' => self::BB,
        'AG' => self::AG,
        'DM' => self::DM,
        'GD' => self::GD,
        'KN' => self::KN,
        'LC' => self::LC,
        'VC' => self::VC,
        'BZ' => self::BZ,
        'GT' => self::GT,
        'SV' => self::SV,
        'HN' => self::HN,
        'NI' => self::NI,
        'CR' => self::CR,
        'PA' => self::PA,
        'CO' => self::CO,
        'VE' => self::VE,
        'GY' => self::GY,
        'SR' => self::SR,
        'UY' => self::UY,
        'PY' => self::PY,
        'BO' => self::BO,
        'PE' => self::PE,
        'EC' => self::EC,
        'CL' => self::CL,
        'AR' => self::AR,
        'FK' => self::FK,
        'GS' => self::GS,
        'SH' => self::SH,
        'AC' => self::AC,
        'TA' => self::TA,
        'EH' => self::EH,
        'MA' => self::MA,
        'DZ' => self::DZ,
        'TN' => self::TN,
        'LY' => self::LY,
        'SD' => self::SD,
        'SS' => self::SS,
        'ET' => self::ET,
        'ER' => self::ER,
        'DJ' => self::DJ,
        'SO' => self::SO,
        'KE' => self::KE,
        'UG' => self::UG,
        'TZ' => self::TZ,
        'RW' => self::RW,
        'BI' => self::BI,
        'MW' => self::MW,
        'ZM' => self::ZM,
        'ZW' => self::ZW,
        'BW' => self::BW,
        'NA' => self::NA,
        'SZ' => self::SZ,
        'LS' => self::LS,
        'MG' => self::MG,
        'MU' => self::MU,
        'SC' => self::SC,
        'KM' => self::KM,
        'YT' => self::YT,
        'RE' => self::RE,
        'MZ' => self::MZ,
        'AO' => self::AO,
        'CD' => self::CD,
        'CG' => self::CG,
        'CF' => self::CF,
        'TD' => self::TD,
        'CM' => self::CM,
        'GQ' => self::GQ,
        'GA' => self::GA,
        'ST' => self::ST,
        'GH' => self::GH,
        'TG' => self::TG,
        'BJ' => self::BJ,
        'NE' => self::NE,
        'BF' => self::BF,
        'ML' => self::ML,
        'SN' => self::SN,
        'GM' => self::GM,
        'GN' => self::GN,
        'GW' => self::GW,
        'CV' => self::CV,
        'SL' => self::SL,
        'LR' => self::LR,
        'CI' => self::CI,
        'NG' => self::NG,
        'MR' => self::MR,
        'AL' => self::AL,
        'AD' => self::AD,
        'BS' => self::BS,
        'BT' => self::BT,
        'BA' => self::BA,
        'BN' => self::BN,
        'KH' => self::KH,
        'CY' => self::CY,
        'IS' => self::IS,
        'KP' => self::KP,
        'LA' => self::LA,
        'LI' => self::LI,
        'LU' => self::LU,
        'MV' => self::MV,
        'MT' => self::MT,
        'MC' => self::MC,
        'MN' => self::MN,
        'ME' => self::ME,
        'MM' => self::MM,
        'MK' => self::MK,
        'SM' => self::SM,
        'RS' => self::RS,
        'TL' => self::TL,
        'GB' => self::GB,
        'VA' => self::VA,
        'YE' => self::YE,
    ];
    
    const AE = '^\+9715\d{8}$';
    const SA = '^\+9665\d{8}$';
    const OM = '^\+9689\d{7}$';
    const KW = '^\+9655\d{7}$';
    const QA = '^\+974[3-6]\d{7}$';
    const BH = '^\+973[3-3]\d{7}$';
    const US = '^\+1\d{10}$';
    const UK = '^\+447\d{9}$';
    const EG = '^\+201\d{9}$';
    const DE = '^\+49(1[5-7]\d{8,9})$';
    const FR = '^\+33[67]\d{8}$';
    const CN = '^\+86(1[3-9]\d{9})$';
    const IN = '^\+91[6789]\d{9}$';
    const AU = '^\+61[4-5]\d{8}$';
    const BR = '^\+55\d{2}9\d{8}$';
    const ZA = '^\+27[6-8]\d{8}$';
    const JP = '^\+81[7-9]0\d{8}$';
    const CA = '^\+1\d{10}$';
    const MX = '^\+52[1-9]\d{9}$';
    const RU = '^\+7[9]\d{9}$';
    const IT = '^\+39[3]\d{9}$';
    const ES = '^\+34[6-7]\d{8}$';
    const NL = '^\+31[6]\d{8}$';
    const SE = '^\+46[7]\d{8}$';
    const NO = '^\+47[4-9]\d{7}$';
    const DK = '^\+45[2-9]\d{7}$';
    const FI = '^\+358[4-5]\d{7,8}$';
    const BE = '^\+32[4]\d{8}$';
    const CH = '^\+41[7]\d{8}$';
    const AT = '^\+43[6]\d{8,9}$';
    const PT = '^\+351[9]\d{8}$';
    const GR = '^\+30[6]\d{9}$';
    const IE = '^\+353[8]\d{8}$';
    const PL = '^\+48[5-7]\d{8}$';
    const CZ = '^\+420[6-7]\d{8}$';
    const HU = '^\+36[2-9]\d{7}$';
    const SK = '^\+421[9]\d{8}$';
    const RO = '^\+40[7]\d{8}$';
    const BG = '^\+359[87]\d{7}$';
    const HR = '^\+385[9]\d{8}$';
    const SI = '^\+386[3-5]\d{7}$';
    const LT = '^\+370[6]\d{7}$';
    const LV = '^\+371[2]\d{7}$';
    const EE = '^\+372[5-7]\d{7}$';
    const TR = '^\+90[5]\d{9}$';
    const IL = '^\+972[5]\d{8}$';
    const JO = '^\+962[7]\d{8}$';
    const LB = '^\+961[3-9]\d{7}$';
    const SY = '^\+963[9]\d{8}$';
    const IQ = '^\+964[7]\d{9}$';
    const IR = '^\+98[9]\d{9}$';
    const PK = '^\+92[3]\d{9}$';
    const BD = '^\+880[1]\d{9}$';
    const LK = '^\+94[7]\d{8}$';
    const NP = '^\+977[9]\d{9}$';
    const AF = '^\+93[7]\d{8}$';
    const UZ = '^\+998[9]\d{8}$';
    const KZ = '^\+7[7]\d{9}$';
    const KG = '^\+996[5-7]\d{8}$';
    const TJ = '^\+992[9]\d{8}$';
    const TM = '^\+993[6]\d{7}$';
    const AZ = '^\+994[5-7]\d{8}$';
    const GE = '^\+995[5-7]\d{8}$';
    const AM = '^\+374[4-9]\d{7}$';
    const BY = '^\+375[2-5]\d{8}$';
    const MD = '^\+373[6-7]\d{7}$';
    const UA = '^\+380[6-7]\d{8}$';
    const TH = '^\+66[6-9]\d{8}$';
    const VN = '^\+84[3-9]\d{8}$';
    const MY = '^\+60[1]\d{8,9}$';
    const SG = '^\+65[8-9]\d{7}$';
    const ID = '^\+62[8]\d{9,10}$';
    const PH = '^\+63[9]\d{9}$';
    const KR = '^\+82[1]\d{8,9}$';
    const TW = '^\+886[9]\d{8}$';
    const HK = '^\+852[5-9]\d{7}$';
    const MO = '^\+853[6]\d{7}$';
    const NZ = '^\+64[2]\d{8,9}$';
    const FJ = '^\+679[7-9]\d{6}$';
    const PG = '^\+675[7]\d{7}$';
    const SB = '^\+677[7-9]\d{6}$';
    const VU = '^\+678[5-7]\d{6}$';
    const NC = '^\+687[7-9]\d{6}$';
    const PF = '^\+689[8-9]\d{7}$';
    const WS = '^\+685[7]\d{6}$';
    const TO = '^\+676[7-9]\d{6}$';
    const KI = '^\+686[7-9]\d{6}$';
    const TV = '^\+688[7-9]\d{6}$';
    const NR = '^\+674[5-7]\d{6}$';
    const PW = '^\+680[6-8]\d{6}$';
    const FM = '^\+691[9]\d{6}$';
    const MH = '^\+692[4-5]\d{6}$';
    const CK = '^\+682[5-7]\d{6}$';
    const NU = '^\+683[4-5]\d{6}$';
    const TK = '^\+690[3-4]\d{6}$';
    const WF = '^\+681[7-9]\d{6}$';
    const AS = '^\+684[7-9]\d{6}$';
    const GU = '^\+671[7-9]\d{6}$';
    const MP = '^\+670[4-5]\d{6}$';
    const VI = '^\+340[7-9]\d{6}$';
    const PR = '^\+787[9]\d{6}$';
    const DO = '^\+1[8-9]\d{9}$';
    const CU = '^\+53[5]\d{7}$';
    const JM = '^\+1[8-9]\d{9}$';
    const HT = '^\+509[3-4]\d{7}$';
    const TT = '^\+1[8-9]\d{9}$';
    const BB = '^\+1[2]\d{9}$';
    const AG = '^\+1[2]\d{9}$';
    const DM = '^\+1[7]\d{9}$';
    const GD = '^\+1[4]\d{9}$';
    const KN = '^\+1[8]\d{9}$';
    const LC = '^\+1[7]\d{9}$';
    const VC = '^\+1[7]\d{9}$';
    const BZ = '^\+501[6]\d{6}$';
    const GT = '^\+502[4-5]\d{7}$';
    const SV = '^\+503[7]\d{7}$';
    const HN = '^\+504[3-4]\d{7}$';
    const NI = '^\+505[8]\d{7}$';
    const CR = '^\+506[6-8]\d{7}$';
    const PA = '^\+507[6]\d{7}$';
    const CO = '^\+57[3]\d{9}$';
    const VE = '^\+58[4]\d{9}$';
    const GY = '^\+592[6]\d{6}$';
    const SR = '^\+597[7]\d{6}$';
    const UY = '^\+598[9]\d{7}$';
    const PY = '^\+595[9]\d{8}$';
    const BO = '^\+591[7]\d{7}$';
    const PE = '^\+51[9]\d{8}$';
    const EC = '^\+593[9]\d{8}$';
    const CL = '^\+56[9]\d{8}$';
    const AR = '^\+54[9]\d{9}$';
    const FK = '^\+500[5]\d{4}$';
    const GS = '^\+500[5]\d{4}$';
    const SH = '^\+290[5]\d{4}$';
    const AC = '^\+247[5]\d{4}$';
    const TA = '^\+290[8]\d{4}$';
    const EH = '^\+212[6]\d{8}$';
    const MA = '^\+212[6-7]\d{8}$';
    const DZ = '^\+213[5-7]\d{8}$';
    const TN = '^\+216[2-5]\d{7}$';
    const LY = '^\+218[9]\d{8}$';
    const SD = '^\+249[9]\d{8}$';
    const SS = '^\+211[9]\d{8}$';
    const ET = '^\+251[9]\d{8}$';
    const ER = '^\+291[7]\d{6}$';
    const DJ = '^\+253[7]\d{7}$';
    const SO = '^\+252[6-7]\d{7}$';
    const KE = '^\+254[7]\d{8}$';
    const UG = '^\+256[7]\d{8}$';
    const TZ = '^\+255[6-7]\d{8}$';
    const RW = '^\+250[7]\d{8}$';
    const BI = '^\+257[6-7]\d{7}$';
    const MW = '^\+265[9]\d{8}$';
    const ZM = '^\+260[9]\d{8}$';
    const ZW = '^\+263[7]\d{8}$';
    const BW = '^\+267[7]\d{7}$';
    const NA = '^\+264[8]\d{7}$';
    const SZ = '^\+268[7]\d{7}$';
    const LS = '^\+266[5-6]\d{7}$';
    const MG = '^\+261[3]\d{8}$';
    const MU = '^\+230[5]\d{7}$';
    const SC = '^\+248[2]\d{6}$';
    const KM = '^\+269[3]\d{6}$';
    const YT = '^\+262[6]\d{8}$';
    const RE = '^\+262[6]\d{8}$';
    const MZ = '^\+258[8]\d{8}$';
    const AO = '^\+244[9]\d{8}$';
    const CD = '^\+243[8-9]\d{8}$';
    const CG = '^\+242[0]\d{8}$';
    const CF = '^\+236[7]\d{7}$';
    const TD = '^\+235[6-7]\d{7}$';
    const CM = '^\+237[6-7]\d{8}$';
    const GQ = '^\+240[2]\d{7}$';
    const GA = '^\+241[0]\d{7}$';
    const ST = '^\+239[9]\d{6}$';
    const GH = '^\+233[2]\d{8}$';
    const TG = '^\+228[9]\d{7}$';
    const BJ = '^\+229[6]\d{7}$';
    const NE = '^\+227[9]\d{7}$';
    const BF = '^\+226[7]\d{7}$';
    const ML = '^\+223[6-7]\d{7}$';
    const SN = '^\+221[7]\d{8}$';
    const GM = '^\+220[3]\d{7}$';
    const GN = '^\+224[6]\d{8}$';
    const GW = '^\+245[9]\d{7}$';
    const CV = '^\+238[9]\d{6}$';
    const SL = '^\+232[7]\d{7}$';
    const LR = '^\+231[4-7]\d{7}$';
    const CI = '^\+225[0]\d{8}$';
    const NG = '^\+234[8]\d{9}$';
    const MR = '^\+222[4]\d{7}$';
    const AL = '^\+355[2-9]\d{7,8}$';
    const AD = '^\+376[0-9]{6}$';
    const BS = '^\+1-242\d{7}$';
    const BT = '^\+975\d{7,8}$';
    const BA = '^\+387\d{8}$';
    const BN = '^\+673\d{7}$';
    const KH = '^\+855\d{8,9}$';
    const CY = '^\+3579\d{7}$';
    const IS = '^\+354\d{7}$';
    const KP = '^\+850\d{6,7}$';
    const LA = '^\+856\d{8}$';
    const LI = '^\+423\d{7}$';
    const LU = '^\+3526\d{8}$';
    const MV = '^\+960\d{7}$';
    const MT = '^\+356\d{8}$';
    const MC = '^\+377\d{8}$';
    const MN = '^\+976\d{8}$';
    const ME = '^\+382\d{8}$';
    const MM = '^\+95\d{8,9}$';
    const MK = '^\+3897\d{7}$';
    const SM = '^\+378\d{6,7}$';
    const RS = '^\+3816\d{7,8}$';
    const TL = '^\+670\d{7}$';
    const GB = '^\+44(7\d{9})$';
    const VA = '^\+379\d{6,7}$';
    const YE = '^\+9677\d{7}$';
}
